"""add voice snapshot and evolution fields

Revision ID: 16b7a072630d
Revises: 9c1f750c7ae5
Create Date: 2026-04-16 21:38:15.051091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b7a072630d'
down_revision: Union[str, None] = '9c1f750c7ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_config', sa.Column('voice_snapshot', sa.Text(), nullable=True))
    op.add_column('integration_config', sa.Column('voice_snapshot_post_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('integration_config', sa.Column('personality_evolution_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_config', 'personality_evolution_log')
    op.drop_column('integration_config', 'voice_snapshot_post_count')
    op.drop_column('integration_config', 'voice_snapshot')
    # ### end Alembic commands ###
