"""add personality fields to config

Revision ID: 4752e61d5374
Revises: 662ee6921e10
Create Date: 2026-04-15 18:44:07.000143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4752e61d5374'
down_revision: Union[str, None] = '662ee6921e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_config', sa.Column('author_name', sa.Text(), nullable=True))
    op.add_column('integration_config', sa.Column('personality_prompt', sa.Text(), nullable=True))
    op.add_column('integration_config', sa.Column('content_guardrails', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_config', 'content_guardrails')
    op.drop_column('integration_config', 'personality_prompt')
    op.drop_column('integration_config', 'author_name')
    # ### end Alembic commands ###
