"""initial schema

Revision ID: 61fcf59aa0a2
Revises: 
Create Date: 2026-04-14 18:09:00.724808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61fcf59aa0a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_event', ['entity_type', 'entity_id'], unique=False)
    op.create_table('campaign',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('topics_json', sa.Text(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('posting_window_start', sa.Text(), nullable=True),
    sa.Column('posting_window_end', sa.Text(), nullable=True),
    sa.Column('duration_rule_json', sa.Text(), nullable=True),
    sa.Column('significance_threshold', sa.Float(), nullable=False),
    sa.Column('source_preferences_json', sa.Text(), nullable=False),
    sa.Column('novelty_cooldown_days', sa.Integer(), nullable=False),
    sa.Column('profile_adherence_override', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_status', 'campaign', ['status'], unique=False)
    op.create_table('historical_linkedin_artifact',
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_payload_json', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historical_artifact_type', 'historical_linkedin_artifact', ['artifact_type'], unique=False)
    op.create_index('idx_historical_external_ref', 'historical_linkedin_artifact', ['external_ref'], unique=False)
    op.create_table('integration_config',
    sa.Column('linkedin_status', sa.String(), nullable=False),
    sa.Column('slack_status', sa.String(), nullable=False),
    sa.Column('llm_status', sa.String(), nullable=False),
    sa.Column('email_status', sa.String(), nullable=False),
    sa.Column('setup_complete', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('daily_post_budget', sa.Integer(), nullable=False),
    sa.Column('min_gap_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_profile',
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_post_count', sa.Integer(), nullable=False),
    sa.Column('source_engagement_sample_count', sa.Integer(), nullable=False),
    sa.Column('voice_traits_json', sa.Text(), nullable=False),
    sa.Column('structure_preferences_json', sa.Text(), nullable=False),
    sa.Column('topic_affinities_json', sa.Text(), nullable=False),
    sa.Column('engagement_patterns_json', sa.Text(), nullable=False),
    sa.Column('adherence_strength', sa.String(), nullable=False),
    sa.Column('profile_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis_version', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_ref',
    sa.Column('secret_name', sa.String(), nullable=False),
    sa.Column('storage_type', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_name')
    )
    op.create_table('daily_run',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('run_date_local', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('degraded_flag', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'run_date_local')
    )
    op.create_table('candidate_opportunity',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('narrative_type', sa.String(), nullable=False),
    sa.Column('source_refs_json', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('global_score', sa.Float(), nullable=True),
    sa.Column('similarity_group_id', sa.String(), nullable=True),
    sa.Column('suppression_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['daily_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_signal',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('title_or_summary', sa.Text(), nullable=True),
    sa.Column('url_or_ref', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('normalized_payload_json', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['daily_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_signal_run_id', 'source_signal', ['run_id'], unique=False)
    op.create_index('idx_source_signal_source_hash', 'source_signal', ['source_hash'], unique=False)
    op.create_table('selected_opportunity',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('selection_rank', sa.Integer(), nullable=False),
    sa.Column('selection_date', sa.Text(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft',
    sa.Column('selected_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('primary_text', sa.Text(), nullable=False),
    sa.Column('alternate_hooks_json', sa.Text(), nullable=True),
    sa.Column('grounding_summary', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('profile_used', sa.Boolean(), nullable=False),
    sa.Column('profile_version_used', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('critic_version', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['selected_opportunity_id'], ['selected_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_draft_selected_version', 'draft', ['selected_opportunity_id', 'version'], unique=False)
    op.create_index('idx_draft_status', 'draft', ['status'], unique=False)
    op.create_table('approval_action',
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('source_surface', sa.String(), nullable=False),
    sa.Column('action_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_post',
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('publish_mode', sa.String(), nullable=False),
    sa.Column('published_text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('manual_confirmation_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_published_post_status', 'published_post', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_published_post_status', table_name='published_post')
    op.drop_table('published_post')
    op.drop_table('approval_action')
    op.drop_index('idx_draft_status', table_name='draft')
    op.drop_index('idx_draft_selected_version', table_name='draft')
    op.drop_table('draft')
    op.drop_table('selected_opportunity')
    op.drop_index('idx_source_signal_source_hash', table_name='source_signal')
    op.drop_index('idx_source_signal_run_id', table_name='source_signal')
    op.drop_table('source_signal')
    op.drop_table('candidate_opportunity')
    op.drop_table('daily_run')
    op.drop_table('secret_ref')
    op.drop_table('personality_profile')
    op.drop_table('integration_config')
    op.drop_index('idx_historical_external_ref', table_name='historical_linkedin_artifact')
    op.drop_index('idx_historical_artifact_type', table_name='historical_linkedin_artifact')
    op.drop_table('historical_linkedin_artifact')
    op.drop_index('idx_campaign_status', table_name='campaign')
    op.drop_table('campaign')
    op.drop_index('idx_audit_entity', table_name='audit_event')
    op.drop_table('audit_event')
    # ### end Alembic commands ###
