"""add media_suggestions to draft

Revision ID: 662ee6921e10
Revises: c85c0b0b33bd
Create Date: 2026-04-15 17:13:36.676579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662ee6921e10'
down_revision: Union[str, None] = 'c85c0b0b33bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('media_suggestions_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'media_suggestions_json')
    # ### end Alembic commands ###
