"""add custom_rss_feeds to campaign

Revision ID: 761d8b31c7dd
Revises: 16b7a072630d
Create Date: 2026-04-16 22:51:06.704133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761d8b31c7dd'
down_revision: Union[str, None] = '16b7a072630d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('custom_rss_feeds_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'custom_rss_feeds_json')
    # ### end Alembic commands ###
