"""add learned_context field

Revision ID: 88b1c96d662e
Revises: 761d8b31c7dd
Create Date: 2026-04-18 14:08:04.055454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b1c96d662e'
down_revision: Union[str, None] = '761d8b31c7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_config', sa.Column('learned_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_config', 'learned_context')
    # ### end Alembic commands ###
