"""add selected_media to draft

Revision ID: 9c1f750c7ae5
Revises: d07b5f1fdc9a
Create Date: 2026-04-16 20:07:31.420052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1f750c7ae5'
down_revision: Union[str, None] = 'd07b5f1fdc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft', sa.Column('selected_media_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft', 'selected_media_json')
    # ### end Alembic commands ###
