"""add post_feedback table

Revision ID: c85c0b0b33bd
Revises: 61fcf59aa0a2
Create Date: 2026-04-15 17:03:03.438669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85c0b0b33bd'
down_revision: Union[str, None] = '61fcf59aa0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_feedback',
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('reposts', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('performance_rating', sa.String(), nullable=True),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_didnt_work', sa.Text(), nullable=True),
    sa.Column('audience_reaction_notes', sa.Text(), nullable=True),
    sa.Column('improvement_notes', sa.Text(), nullable=True),
    sa.Column('effective_elements_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_post_feedback_campaign', 'post_feedback', ['campaign_id'], unique=False)
    op.create_index('idx_post_feedback_draft', 'post_feedback', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_post_feedback_draft', table_name='post_feedback')
    op.drop_index('idx_post_feedback_campaign', table_name='post_feedback')
    op.drop_table('post_feedback')
    # ### end Alembic commands ###
