"""add token_usage table

Revision ID: d07b5f1fdc9a
Revises: 4752e61d5374
Create Date: 2026-04-16 18:06:05.219974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07b5f1fdc9a'
down_revision: Union[str, None] = '4752e61d5374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_usage_created', 'token_usage', ['created_at'], unique=False)
    op.create_index('idx_token_usage_service', 'token_usage', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_usage_service', table_name='token_usage')
    op.drop_index('idx_token_usage_created', table_name='token_usage')
    op.drop_table('token_usage')
    # ### end Alembic commands ###
